# Generated by Django 5.0.7 on 2024-07-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ismi', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telfon_raqami', models.CharField(blank=True, max_length=15, null=True)),
                ('lavozimi', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('javob', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('kutish', 'Kutish'), ('tasdiqlandi', 'Tasdiqlandi'), ('rad etildi', 'Rad etildi')], default='kutish', max_length=20, null=True)),
            ],
        ),
    ]
