# Generated by Django 5.0.7 on 2024-07-26 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0003_alter_application_ismi_alter_application_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='javob',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='updated',
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Qabul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('javob', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('kutish', 'Kutish'), ('tasdiqlandi', 'Tasdiqlandi'), ('rad etildi', 'Rad etildi')], default='kutish', max_length=20, null=True)),
                ('PK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ariza.application')),
            ],
        ),
    ]
