# Generated by Django 5.0.7 on 2024-07-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0004_remove_application_javob_remove_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='lavozimi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
