# Generated by Django 5.0.7 on 2024-07-16 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Spravochniks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(help_text='F.I.SHni kiriting', max_length=200, verbose_name='F.I.SH')),
                ('Stationary', models.CharField(help_text='F.I.SHni kiriting', max_length=250, verbose_name='F.I.SH')),
                ('Mobile', models.CharField(max_length=250)),
                ('creator', models.CharField(max_length=250)),
                ('changer', models.CharField(max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('Branch', models.ForeignKey(blank=True, help_text='Tashkilotni tanlang', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch', verbose_name='Tashkilot')),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department')),
                ('Positions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.positions')),
            ],
            options={
                'verbose_name': 'Spravochnik',
                'verbose_name_plural': 'Spravochniklar',
                'ordering': ['FullName'],
            },
        ),
    ]
